#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t cm"

$L "  o-o"
$L " o   o "
$L " |   | o-o o-o o-o  o-o "
$L " o   o  /  | | |  | |- "
$L "  o-o  o-o o-o o  o o-o"
$L "Welcome to Android `getprop ro.build.version.release` / Ozone-`getprop ro.ozone.version`";
